### ISSUE TITLE
Sunset `sentry-android-okhttp` in favor of `sentry-okhttp`

### ISSUE THREAD

**Issue by romtsn** [getsentry/sentry-android-gradle-plugin#601]
### Description

Since we have introduced pure jvm `sentry-okhttp` module in 7.0.0, we need to sunset its predecessor eventually:

```[tasklist]
### Tasks
- [x] auto-install `sentry-okhttp` instead of `sentry-android-okhttp` when the sdk version is 7.0 and above
- [x] auto-instrument using `io.sentry.okhttp` instead of `io.sentry.android.okhttp` classes when the sdk version is 7.0 and above
- [x] update docs https://docs.sentry.io/platforms/android/integrations/okhttp/
```

**Comment by kahest** [comment]
@stefanosiano is this done?
