### ISSUE TITLE
Migrate `react-native/sentry.gradle` to SAGP

### ISSUE THREAD

**Issue by krystofwoldrich** [getsentry/sentry-android-gradle-plugin#796]
### Description

Migrating `sentry.gradle` to SAGP simplifies RN Android setup and ensure both source maps and native symbols are uploaded by default (currently only source maps uploaded by default).

### Tasks
- [ ] Move sentry.gradle code to SAGP
- [ ] Create new defaults for SAGP on RN
- [ ] Add SAGP as dependency of RN SDK
- [ ] Update @sentry/wizard
- [ ] Update docs manual setup RN

### Benefits

- One plugin for RN users on Android (currently two)
- One options (currently two)
- Sensible defaults (currently RN users have to change SAGP default to avoid unexpected behaviour) 
  - https://docs.sentry.io/platforms/react-native/manual-setup/manual-setup/#enable-sentry-agp
  - auto-install=false need for RN
- Better support for native network requests
  - RN SDK can benefit from bytecode manipulation
- Easier to test the RN specific tasks

**Comment by smellouk** [comment]
Hi Hi, are there any plans for this issue?

**Comment by romtsn** [comment]
yes, it's on the roadmap for the next 3 months, so we should get to it rather soon.
